### ISSUE TITLE
Why is the Enforcer in the rules directory?

### ISSUE THREAD

**Issue by adamaltman** [rolfvreijdenberger/izzum-statemachine#2]
https://github.com/rolfvreijdenberger/izzum-statemachine/blob/master/src/rules/Enforcer.php

Why is the Enforcer in the rules directory?  

And also, why is it in the state machine (it seems to not care about state)?

P.S.  Nice library!

**Comment by rolfvreijdenberger** [comment]
Adam, I removed the enforcer from the 2.0 version
