### ISSUE TITLE
callCallable does not give error if typo in class/methodname 

### ISSUE THREAD

**Issue by clindh** [rolfvreijdenberger/izzum-statemachine#7]
If a callable has been defined in a rule file (json,xml etc) with for example wrong classname, there is no indication neither at load time or later that it can/will not be called - making it hard to find that typo in the FSM definition.   With commands and rules you get an error though ("failed rule creation, class does not exist"). 

How about throwing error in callCallable as well, something like
`if (is_callable($callable)) 
  call_user_func($callable, $context->getEntity());
else
  throw new Exception("failed to call callable $callable for some reason or another`

**Comment by rolfvreijdenberger** [comment]
Hi, thanks for the suggestion.
I think what you mean is to be implemented both for commands and rule: 

- https://github.com/rolfvreijdenberger/izzum-statemachine/blob/master/src/statemachine/Transition.php#L238 for transition logic execution AND rule logic execution
https://github.com/rolfvreijdenberger/izzum-statemachine/blob/master/src/statemachine/State.php#L434 for state exit/entry logic execution

pseudo:
if (callable is defined)
    if(is not callable) { throw exception} else { call() };
else {
    return false
}
return true 

is that correct?

**Comment by clindh** [comment]
Hello

Yes exactly, both places would be useful. I have just started using izzum-statemachine and make all kinds of typos and mistakes :-)  But of course this could be useful in a production enviroment as well, where as a “missed” guard due to a broken PHP load path for example could put the machine into wrong states.

An another improvement would be for a loader to verify that all callables exist, maybe as an option - useful during development but not necessary to do when in production, to avoid loading code into memory.

Thanks for a great machine!

// C



On 28 jun 2016, at 16:06, Rolf Vreijdenberger <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, thanks for the suggestion.
I think what you mean is to be implemented both for commands and rule:

 *   https://github.com/rolfvreijdenberger/izzum-statemachine/blob/master/src/statemachine/Transition.php#L238 for transition logic execution AND rule logic execution https://github.com/rolfvreijdenberger/izzum-statemachine/blob/master/src/statemachine/State.php#L434 for state exit/entry logic execution

pseudo:
if (callable is defined)
if(is not callable) { throw exception} else { call() };
else {
return false
}
return true

is that correct?

**Comment by rolfvreijdenberger** [comment]
I edited my previous reaction during your response: we have the same solution for the Loader thing to check for callables. the same could be implemented with rules and commands ('class_exists' etc).

This can be implemented by for your specific app, i'll look into it (seems like a simple operation to add after a statemachine has been fully loaded by the loader)

the check on the callable, I will add that before end of july
thanks for the suggestion

**Comment by clindh** [comment]
Thanks Rolf, yes something like a verifyMachine that can be performed by a deriver Loader

**Comment by rolfvreijdenberger** [comment]
@clindh can you review e561518 in the develop branch
unittests are in place, no api change.
there is some more work to be done (same config check for rules and commands as currently implemented for callables), but this seems to be what you asked.

**Comment by rolfvreijdenberger** [comment]
request implemented, small refactoring and tested.
clossing issue as solved
